### PR TITLE
add `nix shell` command

### PR DESCRIPTION
**Pull request by tennox**
e.g. 
```
nix shell github:nixos/nixpkgs/407f8825b321617a38b86a4d9be11fd76d513da2#go-task
```

### CODE REVIEW

**Comment by lazamar** [comment]
Thanks!

**Comment by tennox** [comment]
Doesn't seem like it's deployed, is it? 🤔
(No pressure)

**Comment by lazamar** [comment]
@tennox sorry it took forever, but it is finally there.

**Comment by tennox** [comment]
> @tennox sorry it took forever, but it is finally there.

Hehe, thanks 💜

**Pull request merged**
